framework:
   messenger:
      transports:
        async:
          dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
          retry_strategy:
              max_retries: 5

      routing:
        'App\Domain\Service\Mail\QueueMailMessage': async


